# Generated by Django 5.2.17 on 2026-10-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_password_hash_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_type',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
