# Generated by Django 5.2.17 on 2026-10-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_type_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='id',
        ),
    ]
